### ISSUE TITLE
Design Bug in the unusable interface house

### ISSUE THREAD

**Issue by charlie-to** [charlie-to/tk-lab-page#73]
文字がズレていた。
cssのどこかでミスっていると思う。

**Comment by charlie-to** [comment]
こんな感じ。
<img width="1283" alt="image" src="https://github.com/charlie-to/tk-lab-page/assets/62843186/ed488523-8448-496f-90cc-565c47fdf87a">
「が現れた」の位置を変えたい。

**Comment by charlie-to** [comment]
大きめのディスプレイ＆全画面表示で起きた。
本番のことも考えると、ある程度大きいディスプレイにも対応できるように、しっかりレスポンシブデザイン対応するのがいいかも。

**Comment by Futty93** [comment]
逃げていたのがバレた。
